// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcWRC-gfWnWzj6KzZN5K6LCN8PYkvyamg',
    appId: '1:527047979450:web:d9ce03848afea5f4602d83',
    messagingSenderId: '527047979450',
    projectId: 'app-library-3ecf2',
    authDomain: 'app-library-3ecf2.firebaseapp.com',
    storageBucket: 'app-library-3ecf2.appspot.com',
    measurementId: 'G-ST19R39K3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1IvNMVBgdebanngbbYOx_VrBu7cbxc0',
    appId: '1:527047979450:android:a568ec97de03c93e602d83',
    messagingSenderId: '527047979450',
    projectId: 'app-library-3ecf2',
    storageBucket: 'app-library-3ecf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeAYuYJn5YRNoJbXAb9-qVHFGbJdJ16ug',
    appId: '1:527047979450:ios:6967ea9ab54034d3602d83',
    messagingSenderId: '527047979450',
    projectId: 'app-library-3ecf2',
    storageBucket: 'app-library-3ecf2.appspot.com',
    iosClientId: '527047979450-7ib67ahsu4a46kf7mfu42urlm9rq9d0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.appLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeAYuYJn5YRNoJbXAb9-qVHFGbJdJ16ug',
    appId: '1:527047979450:ios:32cb0f8031a4d325602d83',
    messagingSenderId: '527047979450',
    projectId: 'app-library-3ecf2',
    storageBucket: 'app-library-3ecf2.appspot.com',
    iosClientId: '527047979450-9lomgcio1undqrhvuprisikkrl6e72kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appLibrary.RunnerTests',
  );
}
